### PREPROCESSING DATA

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("IPL Matches 2008-2020.csv")
print(dataset.shape)

(816, 17)

In [3]:
#no need for umpire columns
dataset = dataset.iloc[:,0:-2]

In [4]:
dataset

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN

In [5]:
dataset.sort_values(['id']).head(60)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN
5,335987,Jaipur,2008-04-21,SR Watson,Sawai Mansingh Stadium,0,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,N,NaN
6,335988,Hyderabad,2008-04-22,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,N,NaN
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN
8,335990,Hyderabad,2008-04-24,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,NaN
9,335991,Chandigarh,2008-04-25,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,N,NaN
10,335992,Bangalore,2008-04-26,SR Watson,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,7.0,N,NaN
11,335993,Chennai,2008-04-26,JDP Oram,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,9.0,N,NaN
12,335994,Mumbai,2008-04-27,AC Gilchrist,Dr DY Patil Sports Academy,0,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,10.0,N,NaN
13,335995,Chandigarh,2008-04-27,SM Katich,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,bat,Kings XI Punjab,wickets,4.0,N,NaN
14,335996,Bangalore,2008-04-28,MS Dhoni,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,13.0,N,NaN
15,335997,Kolkata,2008-04-29,ST Jayasuriya,Eden Gardens,0,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,bat,Mumbai Indians,wickets,7.0,N,NaN
16,335998,Delhi,2008-04-30,GD McGrath,Feroz Shah Kotla,0,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Daredevils,runs,10.0,N,NaN
17,335999,Hyderabad,2008-05-01,SE Marsh,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,7.0,N,NaN
18,336000,Jaipur,2008-05-01,SA Asnodkar,Sawai Mansingh Stadium,0,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,Rajasthan Royals,runs,45.0,N,NaN
19,336001,Chennai,2008-05-02,V Sehwag,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,Delhi Daredevils,wickets,8.0,N,NaN
20,336002,Hyderabad,2008-05-25,R Vinay Kumar,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN
21,336003,Chandigarh,2008-05-03,IK Pathan,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Kolkata Knight Riders,Kings XI Punjab,bat,Kings XI Punjab,runs,9.0,N,NaN
22,336004,Mumbai,2008-05-04,SM Pollock,Dr DY Patil Sports Academy,0,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,Mumbai Indians,runs,29.0,N,NaN
23,336005,Jaipur,2008-05-04,Sohail Tanvir,Sawai Mansingh Stadium,0,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,bat,Rajasthan Royals,wickets,8.0,N,NaN
24,336006,Bangalore,2008-05-05,S Sreesanth,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,6.0,N,NaN
25,336007,Chennai,2008-05-06,AC Gilchrist,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,7.0,N,NaN
26,336008,Mumbai,2008-05-07,A Nehra,Dr DY Patil Sports Academy,0,Mumbai Indians,Rajasthan Royals,Mumbai Indians,field,Mumbai Indians,wickets,7.0,N,NaN
27,336009,Delhi,2008-05-08,MS Dhoni,Feroz Shah Kotla,0,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,4.0,N,NaN
28,336010,Kolkata,2008-05-08,SC Ganguly,Eden Gardens,0,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,5.0,N,NaN
29,336011,Jaipur,2008-05-09,YK Pathan,Sawai Mansingh Stadium,0,Rajasthan Royals,Deccan Chargers,Rajasthan Royals,field,Rajasthan Royals,wickets,8.0,N,NaN
30,336012,Bangalore,2008-05-28,CRD Fernando,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN
31,336013,Chennai,2008-05-10,L Balaji,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,Chennai Super Kings,runs,18.0,N,NaN
32,336014,Hyderabad,2008-05-11,SC Ganguly,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Kolkata Knight Riders,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,23.0,N,NaN
33,336015,Jaipur,2008-05-11,SR Watson,Sawai Mansingh Stadium,0,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,NaN
34,336016,Chandigarh,2008-05-12,SE Marsh,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Kings XI Punjab,wickets,9.0,N,NaN
35,336017,Kolkata,2008-05-13,Shoaib Akhtar,Eden Gardens,0,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,23.0,N,NaN
36,336018,Mumbai,2008-05-14,ST Jayasuriya,Wankhede Stadium,0,Mumbai Indians,Chennai Super Kings,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN
37,336019,Chandigarh,2008-05-28,SE Marsh,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,Kings XI Punjab,runs,41.0,N,NaN
38,336020,Delhi,2008-05-15,A Mishra,Feroz Shah Kotla,0,Delhi Daredevils,Deccan Chargers,Deccan Chargers,field,Delhi Daredevils,runs,12.0,N,NaN
39,336021,Mumbai,2008-05-16,SM Pollock,Wankhede Stadium,0,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,field,Mumbai Indians,wickets,8.0,N,NaN
40,336022,Delhi,2008-05-17,DPMD Jayawardene,Feroz Shah Kotla,0,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,Kings XI Punjab,runs,6.0,N,D/L
41,336023,Jaipur,2008-05-17,GC Smith,Sawai Mansingh Stadium,0,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Rajasthan Royals,runs,65.0,N,NaN
42,336024,Hyderabad,2008-05-18,DJ Bravo,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Mumbai Indians,Deccan Chargers,field,Mumbai Indians,runs,25.0,N,NaN
43,336025,Kolkata,2008-05-18,M Ntini,Eden Gardens,0,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,Chennai Super Kings,runs,3.0,N,D/L
44,336026,Bangalore,2008-05-19,SP Goswami,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Delhi Daredevils,field,Delhi Daredevils,wickets,5.0,N,NaN
45,336027,Kolkata,2008-05-20,YK Pathan,Eden Gardens,0,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,6.0,N,NaN
46,336028,Mumbai,2008-05-21,SE Marsh,Wankhede Stadium,0,Mumbai Indians,Kings XI Punjab,Mumbai Indians,field,Kings XI Punjab,runs,1.0,N,NaN
47,336029,Chennai,2008-05-21,A Kumble,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,14.0,N,NaN
48,336031,Chandigarh,2008-05-23,SE Marsh,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Deccan Chargers,Kings XI Punjab,field,Kings XI Punjab,wickets,6.0,N,NaN
49,336032,Delhi,2008-05-24,KD Karthik,Feroz Shah Kotla,0,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,field,Delhi Daredevils,wickets,5.0,N,NaN
50,336033,Chennai,2008-05-24,JA Morkel,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,runs,10.0,N,NaN
51,336034,Bangalore,2008-05-03,P Kumar,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,field,Royal Challengers Bangalore,runs,3.0,N,NaN
52,336035,Kolkata,2008-05-25,Umar Gul,Eden Gardens,0,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,bat,Kolkata Knight Riders,wickets,3.0,N,NaN
53,336036,Jaipur,2008-05-26,Sohail Tanvir,Sawai Mansingh Stadium,0,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,field,Rajasthan Royals,wickets,5.0,N,NaN
54,336037,Hyderabad,2008-05-27,SK Raina,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Chennai Super Kings,Deccan Chargers,bat,Chennai Super Kings,wickets,7.0,N,NaN
55,336038,Mumbai,2008-05-30,SR Watson,Wankhede Stadium,0,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,field,Rajasthan Royals,runs,105.0,N,NaN
56,336039,Mumbai,2008-05-31,M Ntini,Wankhede Stadium,0,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,bat,Chennai Super Kings,wickets,9.0,N,NaN
57,336040,Mumbai,2008-06-01,YK Pathan,Dr DY Patil Sports Academy,0,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,NaN
58,392181,Cape Town,2009-04-18,SR Tendulkar,Newlands,1,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,field,Mumbai Indians,runs,19.0,N,NaN
59,392182,Cape Town,2009-04-18,R Dravid,Newlands,1,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,75.0,N,NaN

In [6]:
features_with_na = [features for features in dataset.columns if dataset[features].isnull().sum()>1]
for features in features_with_na : 
    print(features,np.round(dataset[features].isnull().mean(),4), '% missing value')

city 0.0159 % missing value
player_of_match 0.0049 % missing value
winner 0.0049 % missing value
result 0.0049 % missing value
result_margin 0.0208 % missing value
eliminator 0.0049 % missing value
method 0.9767 % missing value

In [7]:
#venues for which city is null
venues_city = pd.unique(dataset[dataset['city'].isnull()]['venue'])
print('Venues for which City value is null : ',venues_city)

Venues for which City value is null :  ['Sharjah Cricket Stadium' 'Dubai International Cricket Stadium']

In [8]:
#checking for each venue ,what are the city values given other then null
unique_city = {}
for ven in venues_city:
    unique_city[ven] = pd.unique(dataset[(dataset['venue'] == ven)&(dataset['city'].notnull())]['city'])
    print("City for ",ven," : ",unique_city[ven])

City for  Sharjah Cricket Stadium  :  ['Sharjah']
City for  Dubai International Cricket Stadium  :  ['Dubai']

In [9]:
#from above we can say there is a unique value of city 
#So we are updating null values with the unique value of city
for ven in venues_city : 
    dataset.loc[dataset['venue'] == ven,'city'] = unique_city[ven][0]

In [10]:
#missing value because due to rain match halted or canceled (winner, result, player_of_match,eliminator)
dataset[dataset['winner'].isnull()]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
241,501265,Delhi,2011-05-21,NaN,Feroz Shah Kotla,0,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,NaN,NaN,NaN,NaN
486,829763,Bangalore,2015-04-29,NaN,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NaN,NaN,NaN
511,829813,Bangalore,2015-05-17,NaN,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,NaN,NaN,NaN,NaN
744,1178424,Bengaluru,2019-04-30,NaN,M.Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NaN,NaN,NaN

In [11]:
#replacing each attribute null value with ''
dataset.loc[dataset['winner'].isnull(),'winner'] = ''
dataset.loc[dataset['result'].isnull(),'result'] = ''
dataset.loc[dataset['player_of_match'].isnull(),'player_of_match'] = ''
dataset.loc[dataset['eliminator'].isnull(),'eliminator'] = ''

In [12]:
#result_margin null value due to rain, tie
dataset[dataset['result_margin'].isnull()].head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
66,392190,Cape Town,2009-04-23,YK Pathan,Newlands,1,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Rajasthan Royals,tie,NaN,Y,NaN
130,419121,Chennai,2010-03-21,J Theron,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,field,Kings XI Punjab,tie,NaN,Y,NaN
241,501265,Delhi,2011-05-21,,Feroz Shah Kotla,0,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,,,NaN,,NaN
328,598004,Hyderabad,2013-04-07,GH Vihari,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Sunrisers Hyderabad,tie,NaN,Y,NaN
341,598017,Bangalore,2013-04-16,V Kohli,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,Royal Challengers Bangalore,tie,NaN,Y,NaN

In [13]:
#replacing null value with -1
dataset.loc[dataset['result_margin'].isnull(),'result_margin'] = -1

In [14]:
#method null for non duckworth-loius
dataset[dataset['method'].isnull()].head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN

#### creating separate dataset according to our database schemas

In [15]:
#DUCKWORTH_LEWIS_MATCHES

In [16]:
pd.unique(dataset['method'])

array([nan, 'D/L'], dtype=object)

In [17]:
DUCKWORTH_LEWIS_MATCHES = dataset[dataset['method'] == 'D/L']['id']

In [18]:
DUCKWORTH_LEWIS_MATCHES.reset_index(drop=True,inplace=True)

In [19]:
DUCKWORTH_LEWIS_MATCHES.name = 'matchID'

In [20]:
#TEAMS

In [21]:
#we can observe mismatch in name of team 'Rising Pune Supergiant'
pd.unique(dataset['team1'])

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [22]:
#changing 'Rising Pune Supergiants' to 'Rising Pune Supergiant' 
dataset.loc[dataset['team1'] == 'Rising Pune Supergiants','team1'] = 'Rising Pune Supergiant'
dataset.loc[dataset['team2'] == 'Rising Pune Supergiants','team2'] = 'Rising Pune Supergiant'
dataset.loc[dataset['winner'] == 'Rising Pune Supergiants','winner'] = 'Rising Pune Supergiant'
dataset.loc[dataset['toss_winner'] == 'Rising Pune Supergiants','toss_winner'] = 'Rising Pune Supergiant'

In [23]:
#grouping by teams and getting only date column. Then spliting by '-' and getting year. 
info = dataset.groupby('team1').first()['date'].apply(lambda x : x.split('-')[0])

In [24]:
#add column in TEAMS relation lastMatchOn

In [25]:
TEAMS = pd.DataFrame()
TEAMS.name = 'TEAMS'
TEAMS['name'] = info.index
TEAMS['createdON'] = info.values
TEAMS['lastMatchOn'] = dataset.groupby('team1').last()['date'].apply(lambda x : x.split('-')[0]).values
TEAMS.reset_index(inplace=True)
TEAMS.rename({'index':'teamID'},axis=1,inplace=True)

In [26]:
#LOCATION

In [27]:
dataset.groupby('venue').first()['city']

venue
Barabati Stadium                                               Cuttack
Brabourne Stadium                                               Mumbai
Buffalo Park                                               East London
De Beers Diamond Oval                                        Kimberley
Dr DY Patil Sports Academy                                      Mumbai
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium      Visakhapatnam
Dubai International Cricket Stadium                              Dubai
Eden Gardens                                                   Kolkata
Feroz Shah Kotla                                                 Delhi
Green Park                                                      Kanpur
Himachal Pradesh Cricket Association Stadium                Dharamsala
Holkar Cricket Stadium                                          Indore
JSCA International Stadium Complex                              Ranchi
Kingsmead                                                       Durban
M Chinnaswamy Stadium                                        Bangalore
M.Chinnaswamy Stadium                                        Bengaluru
MA Chidambaram Stadium, Chepauk                                Chennai
Maharashtra Cricket Association Stadium                           Pune
Nehru Stadium                                                    Kochi
New Wanderers Stadium                                     Johannesburg
Newlands                                                     Cape Town
OUTsurance Oval                                           Bloemfontein
Punjab Cricket Association IS Bindra Stadium, Mohali        Chandigarh
Punjab Cricket Association Stadium, Mohali                  Chandigarh
Rajiv Gandhi International Stadium, Uppal                    Hyderabad
Sardar Patel Stadium, Motera                                 Ahmedabad
Saurashtra Cricket Association Stadium                          Rajkot
Sawai Mansingh Stadium                                          Jaipur
Shaheed Veer Narayan Singh International Stadium                Raipur
Sharjah Cricket Stadium                                        Sharjah
Sheikh Zayed Stadium                                         Abu Dhabi
St George's Park                                        Port Elizabeth
Subrata Roy Sahara Stadium                                        Pune
SuperSport Park                                              Centurion
Vidarbha Cricket Association Stadium, Jamtha                    Nagpur
Wankhede Stadium                                                Mumbai
Name: city, dtype: object

In [28]:
#we can see M.Chinnaswamy Stadium city is Bangalore and Bengaluru
#we can see M.Chinnaswamy Stadium and M Chinnaswamy Stadium 
#which is actually same. So we are updating Bengaluru to Bangalore
#updating M Chinnaswamy Stadium to M.Chinnaswamy Stadium 
#updating 'M.Chinnaswamy Stadium ' to 'M.Chinnaswamy Stadium' 
#updating 'Punjab Cricket Association Stadium, Mohali' to 'Punjab Cricket Association IS Bindra Stadium, Mohali'
#updating 'Subrata Roy Sahara Stadium' to 'Maharashtra Cricket Association Stadium' 
#updating 'St George's Park' to 'St Georges Park' 

dataset.loc[dataset['city'] == 'Bengaluru','city'] = 'Bangalore'
dataset.loc[dataset['venue'] == 'M Chinnaswamy Stadium','venue'] = 'M.Chinnaswamy Stadium'
dataset.loc[dataset['venue'] == 'M.Chinnaswamy Stadium ','venue'] = 'M.Chinnaswamy Stadium'
dataset.loc[dataset['venue'] == 'Punjab Cricket Association Stadium, Mohali','venue'] = 'Punjab Cricket Association IS Bindra Stadium, Mohali'
dataset.loc[dataset['venue'] == 'Subrata Roy Sahara Stadium','venue'] = 'Maharashtra Cricket Association Stadium'
dataset.loc[dataset['venue'] == "St George's Park",'venue'] = 'St Georges Park'

In [29]:
info = dataset.groupby('venue').first()['city']

In [30]:
#Neutral venues inherently mean that the stadium at which the match is played does not belong to the teams participating
#finding neutral venues
neutral_venues = dataset[dataset['neutral_venue'] == 1]['venue']

In [31]:
#Home team for each venue
#some of the stadium names changed to new 
#some stadium have no home team currently due to contract ends (NOT considering)
home_team = {}
home_team['Barabati Stadium'] = 'Deccan Chargers-Kings XI Punjab-Kolkata Knight Riders'
home_team['Brabourne Stadium'] = 'Mumbai Indians-Rajasthan Royals'
home_team['Buffalo Park'] = ''
home_team['De Beers Diamond Oval'] = ''
home_team['Dr DY Patil Sports Academy'] = 'Mumbai Indians-Deccan Chargers-Pune Warriors'
home_team['Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'] = 'Deccan Chargers-Sunrisers Hyderabad-Mumbai Indians-Rising Pune Supergiant'
home_team['Dubai International Cricket Stadium'] = ''
home_team['Eden Gardens'] = 'Kolkata Knight Riders'
home_team['Feroz Shah Kotla'] = 'Delhi Capitals'
home_team['Green Park'] = 'Gujarat Lions'
home_team['Himachal Pradesh Cricket Association Stadium'] = 'Kings XI Punjab'
home_team['Holkar Cricket Stadium'] = 'Kochi Tuskers Kerala-Kings XI Punjab'
home_team['JSCA International Stadium Complex'] = 'Kolkata Knight Riders-Chennai Super Kings'
home_team['Kingsmead'] = ''
home_team['M.Chinnaswamy Stadium'] = 'Royal Challengers Bangalore' 
home_team['MA Chidambaram Stadium, Chepauk'] = 'Chennai Super Kings'
home_team['Maharashtra Cricket Association Stadium'] = 'Pune Warriors-Kings XI Punjab-Rising Pune Supergiant-Chennai Super Kings'
home_team['Nehru Stadium'] = 'Kochi Tuskers Kerala'
home_team['New Wanderers Stadium'] = ''
home_team['Newlands'] = ''
home_team['OUTsurance Oval'] = ''
home_team['Punjab Cricket Association IS Bindra Stadium, Mohali'] = 'Kings XI Punjab'
home_team['Rajiv Gandhi International Stadium, Uppal'] = 'Deccan Chargers-Sunrisers Hyderabad'
home_team['Sardar Patel Stadium, Motera'] = 'Rajasthan Royals'
home_team['Saurashtra Cricket Association Stadium'] = 'Gujarat Lions'
home_team['Sawai Mansingh Stadium'] = 'Rajasthan Royals'
home_team['Shaheed Veer Narayan Singh International Stadium'] = 'Delhi Daredevils'
home_team['Sharjah Cricket Stadium'] = ''
home_team['Sheikh Zayed Stadium'] = ''
home_team['St Georges Park'] = ''
home_team['SuperSport Park'] = ''
home_team['Vidarbha Cricket Association Stadium, Jamtha'] = 'Deccan Chargers'
home_team['Wankhede Stadium'] = 'Mumbai Indians'

In [32]:
#homeTeamID attribute of LOCATION will be of format 'teamID1-teamID2-..' move from old home team to recent home team
LOCATION = pd.DataFrame()
LOCATION.name = 'LOCATION'
LOCATION['venue'] = info.index
LOCATION['city'] = info.values
LOCATION.reset_index(inplace=True)
LOCATION.rename({'index':'venueID'},axis=1,inplace=True)
home_team_idlst = []
for ven in LOCATION['venue'] : 
    tmp = home_team[ven].split('-')
    t_id = '-1'
    for t in tmp : 
        if(t != '') : 
            if(t_id != '-1') : t_id = t_id + "-" + str(TEAMS[TEAMS['name'] == t]['teamID'].values[0])
            else : t_id = str(TEAMS[TEAMS['name'] == t]['teamID'].values[0])
    home_team_idlst.append(t_id)
LOCATION['homeTeamID'] = home_team_idlst

In [33]:
#MATCHES

In [34]:
MATCHES = pd.DataFrame()
MATCHES.nam = 'MATCHES'
MATCHES['matchID'] = dataset['id']
MATCHES['date'] = dataset['date']
MATCHES['venueID'] = dataset['venue'].apply(lambda x : LOCATION[LOCATION['venue'] == x]['venueID'].values[0])
MATCHES['team1'] = dataset['team1'].apply(lambda x : TEAMS[TEAMS['name'] == x]['teamID'].values[0])
MATCHES['team2'] = dataset['team2'].apply(lambda x : TEAMS[TEAMS['name'] == x]['teamID'].values[0])
MATCHES['tossWin'] = dataset['toss_winner'].apply(lambda x : TEAMS[TEAMS['name'] == x]['teamID'].values[0])
MATCHES['tossDecision'] = dataset['toss_decision']
MATCHES['playerOfMatch'] = dataset['player_of_match']
MATCHES['winner'] = dataset['winner'].apply(lambda x : x if(x == '') else TEAMS[TEAMS['name'] == x]['teamID'].values[0])
MATCHES['result'] = dataset['result']
MATCHES['resultMargin'] = dataset['result_margin']

In [35]:
dataset1 = pd.read_csv('IPL Ball-by-Ball 2008-2020.csv')
dataset1.shape

(193468, 18)

In [36]:
pd.unique(dataset1[(dataset1['non_boundary'] == 0) & \
                (((dataset1['batsman_runs'] == 4) & (dataset1['total_runs'] != 4)) | \
                ((dataset1['batsman_runs'] == 6) & (dataset1['total_runs'] != 6)))]['extras_type'])

array(['noballs'], dtype=object)

In [37]:
features_with_na = [features for features in dataset1.columns if dataset1[features].isnull().sum()>1]
for features in features_with_na : 
    print(features,np.round(dataset1[features].isnull().mean(),4), '% missing value')

dismissal_kind 0.9509 % missing value
player_dismissed 0.9509 % missing value
fielder 0.9649 % missing value
extras_type 0.9471 % missing value
bowling_team 0.001 % missing value

In [38]:
#replacing null values of dismissal_kind, player_dismissed, fielder, extras_type to ''
dataset1.loc[dataset1['dismissal_kind'].isnull(),'dismissal_kind'] = ''
dataset1.loc[dataset1['player_dismissed'].isnull(),'player_dismissed'] = ''
dataset1.loc[dataset1['fielder'].isnull(),'fielder'] = ''
dataset1.loc[dataset1['extras_type'].isnull(),'extras_type'] = ''

In [39]:
#matches id whose bowling team value is null 
pd.unique(dataset1[dataset1['bowling_team'].isnull()]['id'])

array([501265, 829763], dtype=int64)

In [40]:
#checking innings played in match
pd.unique(dataset1[dataset1['id'] == 829763]['inning'])

array([1], dtype=int64)

In [41]:
#checking innings played in match
pd.unique(dataset1[dataset1['id'] == 501265]['inning'])

array([1], dtype=int64)

In [42]:
#we can see that matches id are 2 of 4 matches which are cancled due to rain
#updating bowling team with correct value
dataset1.loc[dataset1['id'] == 501265,'bowling_team'] = 'Pune Warriors'
dataset1.loc[dataset1['id'] == 829763,'bowling_team'] = 'Rajasthan Royals'

In [43]:
#ball by ball is not sorted, keep that in mind

In [44]:
#BOUNDARY

In [45]:
pd.unique(dataset1['non_boundary'])

array([0, 1], dtype=int64)

In [46]:
dataset1[dataset1['non_boundary'] == 1].head()

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
7505,336014,1,19,6,LR Shukla,DJ Hussey,RP Singh,6,0,6,1,0,,,,,Kolkata Knight Riders,Deccan Chargers
23749,392226,2,1,3,SM Katich,S Sohal,PJ Sangwan,4,0,4,1,0,,,,,Kings XI Punjab,Delhi Daredevils
47927,501225,2,4,4,R Dravid,SR Watson,R Vinay Kumar,4,0,4,1,0,,,,,Rajasthan Royals,Kochi Tuskers Kerala
54183,501252,2,5,1,CH Gayle,TM Dilshan,J Botha,4,0,4,1,0,,,,,Royal Challengers Bangalore,Rajasthan Royals
55334,501257,1,2,3,PC Valthaty,AC Gilchrist,IK Pathan,4,0,4,1,0,,,,,Kings XI Punjab,Delhi Daredevils

In [47]:
#non_boundary = 1 are observation which looks like boundary but are not,runs are due to overthrow, or running that many runs
#there can be more overthrows then this
#overthrow runs given to batsman
#boundary are were batsman_runs is {4,6}and non_boundary is 0

In [48]:
info = dataset1[(dataset1['non_boundary'] == 0) & \
                ((dataset1['batsman_runs'] == 4) | (dataset1['batsman_runs'] == 6))]

In [49]:
info['bowler'].values

array(['SB Joshi', 'JH Kallis', 'JH Kallis', ..., 'KH Pandya',
       'KA Pollard', 'KA Pollard'], dtype=object)

In [50]:
BOUNDARY = pd.DataFrame()
BOUNDARY.name = 'BOUNDARY'
BOUNDARY['id'] = info.index
BOUNDARY['batsman'] = info['batsman'].values
BOUNDARY['bowler'] = info['bowler'].values
BOUNDARY['runs'] = info['batsman_runs'].values

In [51]:
#EXTRAS

In [52]:
pd.unique(dataset1['extras_type'])

array(['', 'byes', 'wides', 'legbyes', 'noballs', 'penalty'], dtype=object)

In [53]:
info = dataset1[dataset1['extra_runs'] != 0]

In [54]:
info[info['extras_type'] == 'penalty']

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
1613,335988,2,11,6,V Sehwag,S Dhawan,PP Ojha,0,5,5,0,0,,,,penalty,Delhi Daredevils,Deccan Chargers
98262,729309,2,4,2,M Vijay,Q de Kock,SL Malinga,0,7,7,0,0,,,,penalty,Delhi Daredevils,Mumbai Indians

In [55]:
#for matchID = 729309 penalty is penalty+wide ,so changind name from 'penalty' to 'penalty_wides'
info.at[98262,'extras_type'] = 'penalty_wides'

In [56]:
pd.unique(info['extras_type'])

array(['byes', 'wides', 'legbyes', 'noballs', 'penalty', 'penalty_wides'],
      dtype=object)

In [57]:
EXTRAS = pd.DataFrame()
EXTRAS.name = 'EXTRAS'
EXTRAS['id'] = info.index
EXTRAS['runs'] = info['extra_runs'].values
EXTRAS['type'] = info['extras_type'].values
EXTRAS['bowler'] = info['bowler'].values

In [58]:
#WICKET

In [59]:
#some fielder field can be null, as not all dismissal needs fielder. But cannot be null.

In [60]:
info = dataset1[dataset1['is_wicket'] == 1]

In [61]:
WICKET = pd.DataFrame()
WICKET.name = 'WICKET'
WICKET['id'] = info.index
WICKET['dismissalKind'] = info['dismissal_kind'].values
WICKET['playerDismissed'] = info['player_dismissed'].values
WICKET['fielder'] = info['fielder'].values

In [62]:
#BALL BY BALL

In [63]:
BALL_BY_BALL = pd.DataFrame()
BALL_BY_BALL.name = 'BALL BY BALL'
BALL_BY_BALL['matchID'] = dataset1['id'].values
BALL_BY_BALL['inning'] = dataset1['inning'].values
BALL_BY_BALL['overs'] = dataset1['over'].values
BALL_BY_BALL['ball'] = dataset1['ball'].values
BALL_BY_BALL['batsman'] = dataset1['batsman'].values
BALL_BY_BALL['nonStriker'] = dataset1['non_striker'].values
BALL_BY_BALL['bowler'] = dataset1['bowler'].values
BALL_BY_BALL['batsmanRuns'] = dataset1['batsman_runs'].values
BALL_BY_BALL['extraRuns'] = dataset1['extra_runs'].values
BALL_BY_BALL['totalRuns'] = dataset1['total_runs'].values
BALL_BY_BALL['isWicket'] = dataset1['is_wicket'].apply(lambda x : True if(x == 1) else False).values
BALL_BY_BALL.reset_index(inplace=True)
BALL_BY_BALL.rename({'index':'id'},axis=1,inplace=True)

In [64]:
#creating separate file each dataset

In [65]:
BALL_BY_BALL.to_csv('BALL_BY_BALL.csv',index=False)
WICKET.to_csv('WICKET.csv',index=False)
EXTRAS.to_csv('EXTRAS.csv',index=False)
BOUNDARY.to_csv('BOUNDARY.csv',index=False)
MATCHES.to_csv('MATCHES.csv',index=False)
LOCATION.to_csv('LOCATION.csv',index=False)
TEAMS.to_csv('TEAMS.csv',index=False)
DUCKWORTH_LEWIS_MATCHES.to_csv('DUCKWORTH_LEWIS_MATCHES.csv',index=False)

In [66]:
#PREPROCESSING DONE